//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public string BookingID { get; set; }
        public string CusID { get; set; }
        public string MSID { get; set; }
        public string BookingNum { get; set; }
        public string MovieName { get; set; }
        public Nullable<int> BookingCinemaNo { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MovieSchedule MovieSchedule { get; set; }
    }
}
