//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string EmpID { get; set; }
        public string EmpPassword { get; set; }
        public Nullable<int> EmpSalary { get; set; }
        public string EmpPositionID { get; set; }
        public string EmpPosition { get; set; }
        public string EmpFname { get; set; }
        public string EmpSname { get; set; }
        public string EmpHouseNum { get; set; }
        public string EmpMoo { get; set; }
        public string EmpSubDistrict { get; set; }
        public string EmpDistrict { get; set; }
        public string EmpProvince { get; set; }
        public Nullable<int> EmpPostalCode { get; set; }
        public string MovieID { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
