//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string PayID { get; set; }
        public string RevenueID { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<int> PayAmount { get; set; }
        public string PayName { get; set; }
        public Nullable<int> PayCVC { get; set; }
        public Nullable<System.DateTime> PayExpDate { get; set; }
    }
}
