//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue
    {
        public string RevenueID { get; set; }
        public Nullable<System.DateTime> RevenueDate { get; set; }
        public string RevenueUser { get; set; }
        public string RevenueType { get; set; }
        public Nullable<int> RevenuePrice { get; set; }
        public string MovieID { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
